### PR TITLE
Fix/certicatedup

### PR DESCRIPTION
**Pull request by AlexsCode**
Removed Duplicate Certificate Loading.
Testing Criteria completed using the same main code, alternating library dependency master vs fork .

MQTT
- Cloud device Parameter Passed to IoTaap MQTT Instance.
- MQTT Subscription & Unsubscription to topics.
- Sending Unique Parameters to MQTT Instance.
- Receiving MQTT Payloads from MQTT Instance.
- Sending Payloads to devices topic & Events on IoTaap Console.

OTA
- Check for auto update forward revisioning to highest version.
- Check for auto update backward revisioning.
- Check for manual update forward revisioning.
- Check for manual update through 20 revisions. Note each runtime.

Notes:
Behaviour consistent when only the lines to set certificate removed.
When either `wifiClientSecure.stop();` lines are removed then unhandled exception occurs in a repeatable way.
Thus inability to perform the check update function.

Repeatable behaviour also discovered on hardware reset of connected device to create overflow on the uptime within console.

### CODE REVIEW

**Review by igolubic — COMMENTED** [review]
@AlexsCode - can you please do the following test:

- Remove `wifiClientSecure.stop();` from OTA module
- Put something lower for **OTA_CHECK_TIME** in definitions.h  (a few seconds will be fine)
- Do NOT update the firmware version, just let it check a few times 
- In parallel, try to publish data to the cloud (using example code or similar) 

Send me your notes and eventual error messages. 

Also, if you leave `wifiClientSecure.stop();` does it normally work after checking for an update? MQTT client processes and OTA updates are currently handled in the same Task, due to the issues with WiFiClientSecure (only one instance can exist in the system), so I cannot see why it causes issues if `wifiClientSecure.stop();` is removed.

**Comment by AlexsCode** [comment]
Upon the advised testing I could find no corresponding issues caused by removing the wifisecureclient.stop in OTA Module, OTA checks and MQTT publishing were available without these lines. I have added a new commit which removes them. 
I am sending the testing documentation privately to @igolubic.

**Comment by igolubic** [comment]
After a lot of testing, I can confirm that this solution doesn't work as expected. When automatic update check is enabled and `wifiClientSecure.stop();` is not called, the system will fail to check for new updates:

**Log:**
```
[2021-03-07 01:21:22] [INFO] - Message successfully published!
[2021-03-07 01:21:22] [INFO] - Checking for updates
sendRequest code=-7
[2021-03-07 01:21:23] [ERROR] - Cannot check for updates
[2021-03-07 01:21:23] [WARNING] - Not connected to MQTT broker
[2021-03-07 01:21:24] [INFO] - Data stored locally!
```

It will not crash the system, but it will fail to detect the change.

If `wifiClientSecure.stop();` is called, then it successfully checks for updates and if needed it starts the update procedure:

**Log:**
```
[2021-03-07 01:15:35] [INFO] - Checking for updates
sendRequest code=200
[2021-03-07 01:15:38] [INFO] - No new updates
```

In both cases, it will fail to switch back to MQTT publishing instantly (and data will be stored locally), it still takes time to reconfigure wifiClientSecure and reconnect to the MQTT and start publishing. 

One thing is perfectly clear - it acts really weird, and unstable (not because of @AlexsCode changes, but because of the WiFiClientSecure implementation)

**Review by igolubic — CHANGES_REQUESTED** [review]
@tomicacar - can you please take a look. 

I think that for now we can only remove `wifiClientSecure.setCACert( SystemGetCAcertificate());
` and move `wifiClientSecure.setTimeout(12000 / 1000); ` to the mqtt_client.cpp, above `wifiClientSecure.setCACert(SystemGetCAcertificate());`. 

Since update is triggered every 6 hours, just a small percentage of data is stored locally for a short period of time (during update check). 

Tested this implementation locally for some time (with **OTA_CHECK_TIME** set to 120000), and it works fine.

**Review by tomicacar — APPROVED** [review]

**Comment by igolubic** [comment]
> I think that for now we can only remove `wifiClientSecure.setCACert( SystemGetCAcertificate()); ` and move `wifiClientSecure.setTimeout(12000 / 1000); ` to the mqtt_client.cpp, above `wifiClientSecure.setCACert(SystemGetCAcertificate());`.
> 
> Since update is triggered every 6 hours, just a small percentage of data is stored locally for a short period of time (during update check).
> 
> Tested this implementation locally for some time (with **OTA_CHECK_TIME** set to 120000), and it works fine.

@AlexsCode - can you please implement this, so we can close this PR.

**Comment by AlexsCode** [comment]
The above changes have been added, and committed with 81c9e934886e5cfdd52ff5fd2c1aa38fb260f097 . Let me know if you require anything more to close the PR @igolubic

**Review by igolubic — APPROVED** [review]

**Pull request merged**
